"""weather forecast ingestion tables

Revision ID: 35961a27f104
Revises: 6e5d8205a503
Create Date: 2026-06-03 09:38:07.164736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35961a27f104'
down_revision = '6e5d8205a503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_locations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bom_station_id', sa.String(length=40), nullable=True),
    sa.Column('bom_forecast_area_id', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('region_relevance', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_locations')),
    sa.UniqueConstraint('name', name=op.f('uq_weather_locations_name'))
    )
    op.create_table('weather_forecasts',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_period', sa.String(length=20), nullable=False),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('wind_gust_kmh', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_probability_pct', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], name=op.f('fk_weather_forecasts_location_id_weather_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_forecasts'))
    )
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_weather_forecasts_location_for', ['location_id', 'forecast_for'], unique=False)

    op.create_table('weather_observations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('wind_gust_kmh', sa.Float(), nullable=True),
    sa.Column('rainfall_since_9am_mm', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], name=op.f('fk_weather_observations_location_id_weather_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations'))
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index('ix_weather_observations_location_observed', ['location_id', 'observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_observations_location_observed')

    op.drop_table('weather_observations')
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_forecasts_location_for')

    op.drop_table('weather_forecasts')
    op.drop_table('weather_locations')
    # ### end Alembic commands ###
