"""energy market data ingestion tables

Revision ID: 6e5d8205a503
Revises: 6cbb723f0011
Create Date: 2026-06-03 09:20:19.672222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e5d8205a503'
down_revision = '6cbb723f0011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_data_sources_name'))
    )
    op.create_table('energy_demand',
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('demand_mw', sa.Float(), nullable=False),
    sa.Column('demand_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_demand'))
    )
    with op.batch_alter_table('energy_demand', schema=None) as batch_op:
        batch_op.create_index('ix_energy_demand_region_interval', ['region', 'interval_start'], unique=False)

    op.create_table('energy_prices',
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_type', sa.String(length=10), nullable=False),
    sa.Column('price_aud_mwh', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_prices'))
    )
    with op.batch_alter_table('energy_prices', schema=None) as batch_op:
        batch_op.create_index('ix_energy_prices_region_interval', ['region', 'interval_start'], unique=False)

    op.create_table('generation_output',
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_type', sa.String(length=40), nullable=False),
    sa.Column('output_mw', sa.Float(), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_output'))
    )
    with op.batch_alter_table('generation_output', schema=None) as batch_op:
        batch_op.create_index('ix_generation_output_region_interval', ['region', 'interval_start'], unique=False)
        batch_op.create_index('ix_generation_output_region_interval_fuel', ['region', 'interval_start', 'fuel_type'], unique=False)

    op.create_table('generator_submissions',
    sa.Column('station_name', sa.String(length=120), nullable=False),
    sa.Column('unit_id', sa.String(length=40), nullable=False),
    sa.Column('fuel_type', sa.String(length=40), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid_band', sa.Integer(), nullable=False),
    sa.Column('price_aud_mwh', sa.Float(), nullable=False),
    sa.Column('volume_mw', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generator_submissions'))
    )
    with op.batch_alter_table('generator_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_generator_submissions_region_interval', ['region', 'interval_start'], unique=False)

    op.create_table('interconnector_flows',
    sa.Column('interconnector_id', sa.String(length=40), nullable=False),
    sa.Column('from_region', sa.String(length=20), nullable=False),
    sa.Column('to_region', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flow_mw', sa.Float(), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('limit_mw', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interconnector_flows'))
    )
    with op.batch_alter_table('interconnector_flows', schema=None) as batch_op:
        batch_op.create_index('ix_interconnector_flows_from_interval', ['from_region', 'interval_start'], unique=False)
        batch_op.create_index('ix_interconnector_flows_id_interval', ['interconnector_id', 'interval_start'], unique=False)

    op.create_table('price_forecasts',
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('forecast_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_aud_mwh', sa.Float(), nullable=False),
    sa.Column('forecast_type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_forecasts'))
    )
    with op.batch_alter_table('price_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_price_forecasts_region_for', ['region', 'forecast_for'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_price_forecasts_region_for')

    op.drop_table('price_forecasts')
    with op.batch_alter_table('interconnector_flows', schema=None) as batch_op:
        batch_op.drop_index('ix_interconnector_flows_id_interval')
        batch_op.drop_index('ix_interconnector_flows_from_interval')

    op.drop_table('interconnector_flows')
    with op.batch_alter_table('generator_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_generator_submissions_region_interval')

    op.drop_table('generator_submissions')
    with op.batch_alter_table('generation_output', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_output_region_interval_fuel')
        batch_op.drop_index('ix_generation_output_region_interval')

    op.drop_table('generation_output')
    with op.batch_alter_table('energy_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_energy_prices_region_interval')

    op.drop_table('energy_prices')
    with op.batch_alter_table('energy_demand', schema=None) as batch_op:
        batch_op.drop_index('ix_energy_demand_region_interval')

    op.drop_table('energy_demand')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
