"""battery_asset_and_dispatch_event_tables

Revision ID: c57b99cfe393
Revises: ee07eb526ccb
Create Date: 2026-06-05 17:06:41.526798

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c57b99cfe393'
down_revision = 'ee07eb526ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_assets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('capacity_mwh', sa.Float(), nullable=False),
    sa.Column('max_power_mw', sa.Float(), nullable=False),
    sa.Column('roundtrip_eff', sa.Float(), nullable=False),
    sa.Column('min_soc_pct', sa.Float(), nullable=False),
    sa.Column('max_soc_pct', sa.Float(), nullable=False),
    sa.Column('reserve_soc_pct', sa.Float(), nullable=False),
    sa.Column('current_soc_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_battery_assets')),
    sa.UniqueConstraint('name', name=op.f('uq_battery_assets_name'))
    )
    op.create_table('dispatch_events',
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('power_mw', sa.Float(), nullable=False),
    sa.Column('soc_before_pct', sa.Float(), nullable=False),
    sa.Column('soc_after_pct', sa.Float(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('forecast_price', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['battery_assets.id'], name=op.f('fk_dispatch_events_battery_id_battery_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_events'))
    )
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.create_index('ix_dispatch_events_battery_timestamp', ['battery_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.drop_index('ix_dispatch_events_battery_timestamp')

    op.drop_table('dispatch_events')
    op.drop_table('battery_assets')
    # ### end Alembic commands ###
