"""agent_config and agent_session tables

Revision ID: ee07eb526ccb
Revises: eb3b9c51c3f5
Create Date: 2026-06-05 11:51:35.593275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee07eb526ccb'
down_revision = 'eb3b9c51c3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('persona_slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_config')),
    sa.UniqueConstraint('persona_slug', name=op.f('uq_agent_config_persona_slug'))
    )
    op.create_table('agent_session',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('headspace_agent_id', sa.String(length=64), nullable=False),
    sa.Column('embed_url', sa.Text(), nullable=False),
    sa.Column('session_token', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disconnected', 'dead', 'shutdown', name='agent_session_status'), nullable=False),
    sa.Column('last_alive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['agent_config.id'], name=op.f('fk_agent_session_config_id_agent_config')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_session'))
    )
    with op.batch_alter_table('agent_session', schema=None) as batch_op:
        batch_op.create_index('ix_agent_session_active_config', ['config_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_session', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_session_active_config', postgresql_where=sa.text("status = 'active'"))

    op.drop_table('agent_session')
    op.drop_table('agent_config')
    op.execute("DROP TYPE IF EXISTS agent_session_status")
    # ### end Alembic commands ###
