"""solcast solar forecast ingestion tables

Revision ID: f7cf7bc31bf2
Revises: 35961a27f104
Create Date: 2026-06-03 09:56:34.956137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cf7bc31bf2'
down_revision = '35961a27f104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_locations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('region_relevance', sa.String(length=40), nullable=False),
    sa.Column('reference_pv_capacity_kw', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solar_locations')),
    sa.UniqueConstraint('name', name=op.f('uq_solar_locations_name'))
    )
    op.create_table('solar_forecasts',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_period', sa.String(length=20), nullable=False),
    sa.Column('ghi_wm2', sa.Float(), nullable=True),
    sa.Column('dni_wm2', sa.Float(), nullable=True),
    sa.Column('dhi_wm2', sa.Float(), nullable=True),
    sa.Column('cloud_opacity_pct', sa.Float(), nullable=True),
    sa.Column('air_temp_c', sa.Float(), nullable=True),
    sa.Column('estimated_pv_output_kw', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['solar_locations.id'], name=op.f('fk_solar_forecasts_location_id_solar_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solar_forecasts'))
    )
    with op.batch_alter_table('solar_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_solar_forecasts_location_for', ['location_id', 'forecast_for'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_solar_forecasts_location_for')

    op.drop_table('solar_forecasts')
    op.drop_table('solar_locations')
    # ### end Alembic commands ###
