"""controllable_load_and_demand_response_event_tables

Revision ID: ff5afed62dc6
Revises: c57b99cfe393
Create Date: 2026-06-05 17:24:09.633942

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ff5afed62dc6'
down_revision = 'c57b99cfe393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllable_loads',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('load_type', sa.String(length=40), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=False),
    sa.Column('curtailment_cost', sa.Float(), nullable=False),
    sa.Column('min_duration_min', sa.Integer(), nullable=False),
    sa.Column('max_duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('curtailed_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controllable_loads')),
    sa.UniqueConstraint('name', name=op.f('uq_controllable_loads_name'))
    )
    op.create_table('demand_response_events',
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['controllable_loads.id'], name=op.f('fk_demand_response_events_load_id_controllable_loads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_response_events'))
    )
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.create_index('ix_demand_response_events_load_timestamp', ['load_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.drop_index('ix_demand_response_events_load_timestamp')

    op.drop_table('demand_response_events')
    op.drop_table('controllable_loads')
    # ### end Alembic commands ###
